// Loads the region boundaries generated by backend/scripts/build_region_geodata.py
export async function loadRegionGeo() {
  const res = await fetch("/data/regions.geojson");
  if (!res.ok) throw new Error(`Boundary file not found (HTTP ${res.status})`);
  return res.json(); // throws if the file isn't valid JSON
}